### ISSUE TITLE
Old Issue for D3

### ISSUE THREAD

**Issue by Alex-Craig** [Berea-CS-Courses/capstone-project-Alex-Craig#7] opened 2021-03-09 19:25 UTC
I have completed a small portion of my code and was able to create a GIF of what I have so far. I understand the GIF is fast but all that's happening is that it is randomly finding a restaurant, loading a GIF and displaying directions when clicked.

**Updated GIF**
![App Testing](https://user-images.githubusercontent.com/46610322/111745201-aa48c380-8862-11eb-9d86-9aa106e33b81.gif)

**Comment by schweinsbergs** [comment] 2021-03-16 17:28
I think that this app is still valid, and that it does what it's supposed to do, which is randomly select a restaurant based on a list. However, I think some of the updates that you've made due to the shortcut app's limitations have eroded some of the convenience of the user. The user having to input all the different options, for example. I think it limits your userbase, from your average Joe to those who are comfortable to the shortcuts app. 

Otherwise, I see that you've got your eye on the ball here, and you're very goal based. You have a lot going good here, you've got a solid foundation and you've done a lot of research.  I like the coding you've done so far, looking at what you need to do.

**Comment by robinsonkal** [comment] 2021-03-16 17:36
Looks good. Maybe a small data flow is in order since some small things like location and input data are being transferred from user to app to google API. Other than that looks good, good first prototypes.

**Comment by jazzij** [comment] 2021-03-19 17:33
I think the shortcuts app works as a clever prototyping tool, but will not be sufficient for your final app. There are too many core features that you can't accomplish with only the shortcuts.

**Comment by jazzij** [comment] 2021-03-19 17:37
A good user flow diagram would also be very helpful to map out the user goals (select restaurant, make a decision, view options, etc) and how they are accomplished on the app. 
Also, it seems like you've put the content of the deliverable in the issue, but you should make a D3.md file and put in in the Deliverables folder. The Issue is just to describe what you have submitted and receive comments.

**Comment by Bryar-Frank** [comment] 2021-03-25 17:48
Good job on your use of GIF to display how the application. It does well to depict how the app is intended to look/be used on the User's end. Its great that your also added in a User Task Flow Diagram; however, a more detailed diagram would be a great starting point to beneficially breaking down each part of the application and its components interactions. As for your answer to the question, "What lingering questions do you have regarding modeling or prototyping?": When it comes to User Task Flow Diagrams, the back end stuff isn't represented as well because it only highlights the user's end of the working components. If you wanted to show each of the background components more, a Entity-Relationship Diagram or Data Flow Diagram would be a good way to highlight that. 

As for what Dr. Jones mentioned earlier, for future assignments, please put changes/documentation in the branch that the Issue is connected to, and not the Issues themselves. Also, please do not merge branches until there is feedback left giving approval to merge branch. 

Otherwise, Great Job!

**Comment by alfarozavalae** [comment] 2021-04-07 03:51
Hello Alex, it seems like you read the feedback in this issue and moved this from in progress to Done. If nothing else is needed here please close this issue.

**Closed as completed** 2021-04-08 11:36 UTC
